SELECT
    EMAIL.ID,
    EMAIL.PARENT_ID,
    EMAIL.MESSAGE_ID,
    EMAIL.SUBJECT,
    EMAIL.IN_REPLY_TO,
    EMAIL.SENT_FROM,
    EMAIL.DATE,
    EMAIL.BODY,
    EMAIL.HIDDEN
FROM EMAIL
WHERE EMAIL.ID = ?
