CREATE TABLE EMAIL (
    MESSAGE_ID VARCHAR(255) PRIMARY KEY,
    SUBJECT VARCHAR(1024),
    IN_REPLY_TO VARCHAR(255),
    SENT_FROM VARCHAR(255),
    DATE TIMESTAMP WITH TIME ZONE,
    BODY LONGTEXT,
    HIDDEN BOOL NOT NULL DEFAULT FALSE
);
CREATE TABLE EMAIL_TAG (
    MESSAGE_ID VARCHAR(255) NOT NULL REFERENCES EMAIL(MESSAGE_ID),
    TAG VARCHAR(255) NOT NULL,
    PRIMARY KEY (MESSAGE_ID, TAG)
);